name: Unit tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  unit_tests:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd test/unit
          python -m uttest test_utils
        
